### ISSUE TITLE
UUID error

### ISSUE THREAD

**Issue by laerm0** [googlefonts/diffbrowsers#18]
```
Traceback (most recent call last):
  File "/Users/stupakm/venvs/type-tools-py3/bin/gfdiffbrowsers", line 11, in <module>
    load_entry_point('gfdiffbrowsers==0.1.4', 'console_scripts', 'gfdiffbrowsers')()
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/diffbrowsers/__main__.py", line 81, in main
    diffbrowsers.new_session(fonts_before, args.fonts_after)
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/diffbrowsers/diffbrowsers.py", line 55, in new_session
    self.gf_regression.new_session(fonts_before, fonts_after)
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/diffbrowsers/gfregression.py", line 54, in new_session
    logger.info("Fonts have been uploaded, uuid: %s" % self.info['uuid'])
KeyError: 'uuid'
```

I initially thought this was a browserstack authorization issue, but it looks like the break here is at uploading the file to gfregression.

**Comment by laerm0** [comment]
bummmp

**Comment by laerm0** [comment]
This works when I diff a font against what's currently online (i.e. `-gf` option) but uploading two fonts (`-fb`) fails.
