### ISSUE TITLE
Diffbrowser having issues again

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/diffbrowsers#29]
```
INFO:__main__:Running browser previews
INFO:diffbrowsers.gfregression:Posting fonts to GF Regression
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gftools-qa.py", line 549, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gftools-qa.py", line 532, in main
    qa.browser_previews()
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gftools-qa.py", line 270, in browser_previews
    diff_browsers.new_session(font_group, font_group)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/diffbrowsers/diffbrowsers.py", line 55, in new_session
    self.gf_regression.new_session(fonts_before, fonts_after)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/diffbrowsers/gfregression.py", line 55, in new_session
    self.info = request.json()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by m4rc1e** [comment]
Apologies. Please try now.

The database instance crashed last night (first ever in four years). I've now rebooted it.

**Comment by RosaWagner** [comment]
Thank you !!
